# Generated by Django 2.2.4 on 2020-01-13 04:01

from django.db import migrations


def set_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        if not flat.construction_year:
            continue

        flat.new_building = flat.construction_year >= 2015

        flat.save()


def reset_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.all():
        flat.new_building = None

        flat.save()


class Migration(migrations.Migration):
    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(set_new_building, reset_new_building),
    ]
