# Generated by Django 2.2.4 on 2020-01-13 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0005_auto_20200113_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='likers',
            field=models.ManyToManyField(blank=True, null=True, related_name='flats', to=settings.AUTH_USER_MODEL, verbose_name='Кому понравилось'),
        ),
    ]
